name: CI
on:
  push:
    branches:
      - main

jobs:
  job:
    name: Test MacOS docker
    runs-on: macos-latest
    timeout-minutes: 45
    steps:

      - name: 'Setup: checkout project'
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          set -e
          brew install docker
          colima start
          docker ps
          docker images
          docker run --rm ubuntu:latest echo "test"
          
